/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ark: {
          bg: '#F1F4F9',
          surface: '#ffffff',
          'surface-alt': '#F5F7FA',
          border: '#E3E6ED',
          'border-strong': '#C5CAD3',
          ink: '#212332',
          'ink-muted': '#69707F',
          'ink-subtle': '#9AA0AC',
          'nav-bg': '#212C3D',
          'nav-bg-alt': '#1A2333',
          'nav-ink': '#E1E5EE',
          'nav-ink-muted': '#8A93A6',
          azure: '#008FBE',
          'azure-dark': '#006C90',
          'azure-light': '#D6EEF7',
          'azure-faint': '#F1F8FB',
          'marker-red': '#E11A22',
          'marker-red-dark': '#B81219',
          'marker-red-light': '#FDE4E5',
          success: '#1FAB6B',
          'success-bg': '#E3F6EE',
          warning: '#F4A100',
          'warning-bg': '#FFF3D6',
          danger: '#E11A22',
          'danger-bg': '#FDE4E5',
          info: '#008FBE',
          'info-bg': '#D6EEF7',
          ai: '#7E57C2',
          'ai-light': '#EDE7F6',
          'ai-faint': '#F6F3FB',
        },
      },
      fontFamily: {
        sans: ['Roboto', '"Helvetica Neue"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"Roboto Mono"', '"SF Mono"', 'Consolas', 'monospace'],
      },
      borderRadius: {
        ark: '4px',
        'ark-2': '6px',
        'ark-3': '8px',
      },
      boxShadow: {
        'ark-1': '0 1px 2px rgba(33,35,50,0.08), 0 1px 3px rgba(33,35,50,0.06)',
        'ark-2': '0 2px 6px rgba(33,35,50,0.10), 0 4px 12px rgba(33,35,50,0.06)',
        'ark-3': '0 8px 24px rgba(33,35,50,0.14), 0 2px 6px rgba(33,35,50,0.08)',
      },
      keyframes: {
        'ark-spin': { to: { transform: 'rotate(360deg)' } },
        'ark-pulse': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
        'ark-shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'ark-fadein': { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'ark-slidein': { from: { opacity: '0', transform: 'translateX(-8px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
      },
      animation: {
        'ark-spin': 'ark-spin 1s linear infinite',
        'ark-pulse': 'ark-pulse 2s ease-in-out infinite',
        'ark-shimmer': 'ark-shimmer 1.5s ease-in-out infinite',
        'ark-fadein': 'ark-fadein 0.25s ease-out',
        'ark-slidein': 'ark-slidein 0.25s ease-out',
      },
    },
  },
  plugins: [],
};
